### ISSUE TITLE
error in package

### ISSUE THREAD

**Issue by leyaocty** [krux02/assimp#5]
Hi, 

I found one mistake in file Types.go line-104:

```
func (v *Quaternion) W() float32 {
	return float32(v.x)
}
```
where return value shall befloat32(v.w).

BTW, I added one method for Bone in Mesh.go to get offset matrix from model with skeletal animation:
```
func (b *Bone) OffsetMatrix() Matrix4x4 {
	return Matrix4x4(b.mOffsetMatrix)
}
```
I tried it for skeletal animation loading and it looks well, so would you please update it into your package?

**Comment by krux02** [comment]
Thanks for the reminder, I will update the package. You can also make a PR (less work for me and you will be listed as contributor ;-)

**Comment by krux02** [comment]
why did you close the issues?

**Comment by krux02** [comment]
I don't know why you closed the issue. But I just pushed changes that implement your suggestions. If you are still interested in making a PR, there is still an easy target. You can make this package a module. This code predates the existence of modules.

**Comment by leyaocty** [comment]
Sorry to reply so late, I just see your reply so I closed my issue. Next time I may make PR for any new issues.

















At 2022-01-21 08:20:38, "Arne Döring" ***@***.***> wrote:

I don't know why you closed the issue. But I just pushed changes that implement your suggestions. If you are still interested in making a PR, there is still an easy target. You can make this package a module. This code predates the existence of modules.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
